"""
agents/report_agent.py
Report generation agent: consolidates all pipeline findings into a
structured Markdown penetration-testing report.

Design principle:
  - Structured sections (tables, finding blocks) are built directly
    from RTAIState data in Python — no LLM hallucination risk.
  - Narrative sections (Executive Summary, Recommendations, Conclusion)
    are generated by the LLM, given the structured data as context.
  - The two halves are stitched together and written to disk.
"""
from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from typing import Any

from langchain_core.messages import HumanMessage, SystemMessage

from agents.base_agent import BaseAgent
from core.config import Config
from core.state import RTAIState


# Risk ordering used to sort findings tables
_RISK_ORDER = {"critical": 0, "high": 1, "medium": 2, "low": 3, "n/a": 4}


class ReportAgent(BaseAgent):
    role = "Penetration Test Report Writer"
    goal = (
        "Produce a clear, professional penetration-testing report that an "
        "executive can skim and a technical engineer can act on."
    )

    def run(self, state: RTAIState) -> dict[str, Any]:
        # ── Structured sections (Python-built, deterministic) ──────────────
        recon_section        = self._build_recon_section(state)
        osint_section        = self._build_osint_section(state)
        exploit_section      = self._build_exploit_section(state)
        remediation_section  = self._build_remediation_section(state)

        # ── Narrative sections (LLM-generated) ────────────────────────────
        narrative = self._generate_narrative(state, osint_section, exploit_section,
                                             remediation_section)

        # ── Assemble full report ───────────────────────────────────────────
        date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        report_md = "\n\n".join([
            self._header(state, date_str),
            narrative["executive_summary"],
            self._scope_section(state, date_str),
            recon_section,
            osint_section,
            exploit_section,
            remediation_section,
            narrative["conclusion"],
            self._footer(date_str),
        ])

        # ── Jira integration ───────────────────────────────────────────────
        jira_section = self._create_jira_ticket(state)
        if jira_section:
            report_md = report_md + "\n\n" + jira_section

        # ── Persist to disk ────────────────────────────────────────────────
        safe_name = re.sub(r"[^\w\-]", "_", state.engagement_name or "engagement")
        report_path = Config.REPORT_DIR / f"{safe_name}_{date_str}_report.md"
        report_path.write_text(report_md, encoding="utf-8")

        return {
            "report": report_md,
            "current_step": "report_complete",
            "finished": True,
        }

    # =========================================================================
    # Structured section builders
    # =========================================================================

    def _header(self, state: RTAIState, date_str: str) -> str:
        return (
            f"# Penetration Test Report\n\n"
            f"| Field | Value |\n"
            f"|---|---|\n"
            f"| **Engagement** | {state.engagement_name or 'N/A'} |\n"
            f"| **Target** | `{state.target}` |\n"
            f"| **Date** | {date_str} |\n"
            f"| **Classification** | CONFIDENTIAL |\n"
        )

    def _scope_section(self, state: RTAIState, date_str: str) -> str:
        from core.config import Config
        osint_tool = "searchsploit + local SQLite CVE DB" if Config.USE_LOCAL_OSINT else "Tavily Search API"
        llm_backend = f"Ollama ({Config.LOCAL_LLM_MODEL})" if Config.USE_LOCAL_LLM else "OpenAI LLM"
        osint_stage = (
            "OSINT intelligence gathering (searchsploit)" if Config.USE_LOCAL_OSINT
            else "OSINT intelligence gathering (Tavily)"
        )
        return (
            "## Scope & Methodology\n\n"
            f"- **Target scope:** `{state.target}`\n"
            f"- **Assessment date:** {date_str}\n"
            f"- **Methodology:** Automated pipeline — Reconnaissance (Nmap) → "
            f"{osint_stage} → Exploitation analysis → "
            "Remediation planning → Report\n"
            f"- **Tools:** python-nmap, {osint_tool}, {llm_backend}\n"
        )

    def _build_recon_section(self, state: RTAIState) -> str:
        recon = next((f for f in state.findings if f.get("phase") == "recon"), None)
        if not recon:
            return "## Reconnaissance\n\n_No recon data available._"

        nmap_data = recon.get("nmap_raw", {})
        hosts = nmap_data.get("hosts", [])

        lines = ["## Reconnaissance\n"]
        if not hosts:
            lines.append("_No live hosts discovered._")
            return "\n".join(lines)

        for host in hosts:
            hostname = host.get("hostname") or host.get("host", "")
            lines.append(f"### Host: `{host.get('host')}` ({hostname})\n")
            lines.append(f"**State:** {host.get('state', 'unknown')}\n")

            # OS guesses
            os_matches = host.get("os_matches", [])
            if os_matches:
                lines.append("**OS Detection:**")
                for os in os_matches:
                    lines.append(f"- {os.get('name')} (accuracy: {os.get('accuracy')}%)")
                lines.append("")

            # Ports table
            ports = host.get("ports", [])
            if ports:
                lines.append("| Port | Protocol | Service | Product | Version |")
                lines.append("|---|---|---|---|---|")
                for p in ports:
                    lines.append(
                        f"| {p.get('port')} | {p.get('protocol')} | "
                        f"{p.get('service', '')} | {p.get('product', '')} | "
                        f"{p.get('version', '')} |"
                    )
                lines.append("")

        # LLM recon analysis
        llm_analysis = recon.get("llm_analysis", "")
        if llm_analysis:
            lines.append("### Recon Analysis\n")
            lines.append(llm_analysis)

        return "\n".join(lines)

    def _build_osint_section(self, state: RTAIState) -> str:
        osint = next((f for f in state.findings if f.get("phase") == "osint"), None)
        if not osint:
            return "## OSINT Intelligence\n\n_No OSINT data available._"

        lines = ["## OSINT Intelligence\n"]

        services = osint.get("services_researched", [])
        if services:
            lines.append(f"**Services researched:** {', '.join(f'`{s}`' for s in services)}\n")

        # Top 3 risks table (structured data from OsintAgent)
        top_3 = osint.get("top_3_risks", [])
        if top_3:
            lines.append("### Top 3 High-Risk Findings\n")
            lines.append("| Rank | Service | Type | Identifier | CVSS | Description | Source |")
            lines.append("|---|---|---|---|---|---|---|")
            for r in sorted(top_3, key=lambda x: x.get("rank", 99)):
                src = r.get("source_url", "N/A")
                src_cell = f"[link]({src})" if src.startswith("http") else src
                lines.append(
                    f"| {r.get('rank')} | {r.get('service')} | {r.get('type')} | "
                    f"`{r.get('identifier')}` | {r.get('cvss')} | "
                    f"{r.get('description')} | {src_cell} |"
                )
            lines.append("")

        # Analyst synthesis
        synthesis = osint.get("llm_synthesis", "")
        if synthesis:
            lines.append("### OSINT Analyst Summary\n")
            lines.append(synthesis)

        return "\n".join(lines)

    def _build_exploit_section(self, state: RTAIState) -> str:
        exploit = next(
            (f for f in state.findings if f.get("phase") == "exploit_analysis"), None
        )
        if not exploit:
            return "## Exploitation Analysis\n\n_No exploitation analysis available._"

        lines = [
            "## Exploitation Analysis\n",
            exploit.get("attack_vectors", "_No attack vectors recorded._"),
        ]
        return "\n".join(lines)

    def _build_remediation_section(self, state: RTAIState) -> str:
        remediation_finding = next(
            (f for f in state.findings if f.get("phase") == "remediation"), None
        )
        if not remediation_finding:
            return "## Remediation Plan\n\n_No remediation data available._"

        remediations: list[dict[str, Any]] = remediation_finding.get("remediations", [])
        if not remediations:
            return "## Remediation Plan\n\n_No attack vectors required remediation._"

        lines = ["## Remediation Plan\n"]

        # Summary table — one row per finding, sorted Critical-first
        lines.append("| # | Title | Risk | Service | CVE |")
        lines.append("|---|---|---|---|---|")
        for r in remediations:
            lines.append(
                f"| {r.get('id')} | {r.get('title')} | **{r.get('risk_level')}** | "
                f"{r.get('service')} | `{r.get('cve')}` |"
            )
        lines.append("")

        # Detailed subsection per remediation
        for r in remediations:
            lines.append(f"### {r.get('id')}. {r.get('title')}\n")
            lines.append(f"**Risk:** {r.get('risk_level')} &nbsp;|&nbsp; "
                         f"**Service:** {r.get('service')} &nbsp;|&nbsp; "
                         f"**CVE:** `{r.get('cve')}`\n")

            steps = r.get("steps", [])
            if steps:
                lines.append("**Steps:**")
                for i, step in enumerate(steps, 1):
                    lines.append(f"{i}. {step}")
                lines.append("")

            snippet = r.get("code_snippet")
            if snippet:
                lines.append("**Commands / Config:**")
                lines.append("```bash")
                lines.append(snippet)
                lines.append("```\n")

            verification = r.get("verification")
            if verification and verification != "N/A":
                lines.append(f"**Verification:** `{verification}`\n")

        return "\n".join(lines)

    def _footer(self, date_str: str) -> str:
        tier = getattr(Config, "LICENSE_TIER", "Community")
        return (
            "---\n\n"
            f"*RTAI Enterprise v1.0 — {tier} Edition &nbsp;|&nbsp; "
            f"Generated: {date_str} &nbsp;|&nbsp; "
            "Classification: CONFIDENTIAL &nbsp;|&nbsp; "
            "For authorised use only.*"
        )

    # =========================================================================
    # LLM narrative generator
    # =========================================================================

    def _generate_narrative(
        self,
        state: RTAIState,
        osint_section: str,
        exploit_section: str,
        remediation_section: str,
    ) -> dict[str, str]:
        """
        Ask the LLM to write two narrative sections.
        Returns a dict with keys: executive_summary, conclusion.
        (Recommendations are now covered by the structured Remediation Plan section.)
        """
        osint_finding   = next((f for f in state.findings if f.get("phase") == "osint"), {})
        exploit_finding = next(
            (f for f in state.findings if f.get("phase") == "exploit_analysis"), {}
        )
        remediation_finding = next(
            (f for f in state.findings if f.get("phase") == "remediation"), {}
        )

        top_3_risks    = osint_finding.get("top_3_risks", [])
        attack_vectors = exploit_finding.get("attack_vectors", "None")
        remediations   = remediation_finding.get("remediations", [])

        has_findings = (
            bool(top_3_risks)
            or (attack_vectors not in ("None", "", "none"))
            or bool(remediations)
        )
        if not has_findings:
            no_findings_instruction = (
                "CRITICAL INSTRUCTION: The Scout and Analyst agents found NO vulnerabilities "
                "on this target. You MUST NOT generate, invent, or hallucinate any security "
                "findings, CVEs, risk ratings, or attack vectors. "
                "The Executive Summary MUST clearly state: "
                "'Environment Secure — No Critical Vulnerabilities Detected.' "
                "Do not reference any specific CVEs, ports, or services that were not "
                "explicitly provided in the data above.\n\n"
            )
        else:
            no_findings_instruction = ""

        messages = [
            SystemMessage(content=self._system_prompt()),
            HumanMessage(
                content=(
                    f"{no_findings_instruction}"
                    f"Engagement: {state.engagement_name}\n"
                    f"Target: {state.target}\n\n"
                    f"Top 3 OSINT risks:\n{self._fmt(top_3_risks)}\n\n"
                    f"Attack vectors:\n{attack_vectors}\n\n"
                    f"Remediation plan summary ({len(remediations)} items):\n"
                    f"{self._fmt([{'id': r.get('id'), 'title': r.get('title'), 'risk_level': r.get('risk_level')} for r in remediations])}\n\n"
                    "Write two sections of a penetration-testing report.\n"
                    "Return ONLY valid JSON (no markdown fences) in this shape:\n"
                    "{\n"
                    '  "executive_summary": "## Executive Summary\\n\\n<content>",\n'
                    '  "conclusion": "## Conclusion\\n\\n<content>"\n'
                    "}\n\n"
                    "Guidelines:\n"
                    "- Executive Summary: 3-5 sentences for a non-technical audience; "
                    "  state the overall risk posture, number of critical/high findings, "
                    "  and that a full remediation plan is included.\n"
                    "- Conclusion: 2-3 sentences wrapping up the engagement and encouraging "
                    "  re-testing after remediations are applied.\n"
                )
            ),
        ]
        response = self.llm.invoke(messages)

        try:
            parsed = json.loads(response.content)
            return {
                "executive_summary": parsed.get("executive_summary",
                                                "## Executive Summary\n\n_Not generated._"),
                "conclusion":        parsed.get("conclusion",
                                                "## Conclusion\n\n_Engagement complete._"),
            }
        except (json.JSONDecodeError, KeyError):
            return {
                "executive_summary": f"## Executive Summary\n\n{response.content}",
                "conclusion":        "## Conclusion\n\n_Engagement complete._",
            }

    # =========================================================================
    # Jira integration
    # =========================================================================

    @staticmethod
    def _create_jira_ticket(state: RTAIState) -> str:
        """
        If ``Config.ENABLE_JIRA_INTEGRATION`` is True and FixerAgent produced
        at least one fix, create a Jira ticket for the highest-risk finding.

        Returns a Markdown section string to append to the report, or an
        empty string if Jira is disabled or ticket creation fails.
        """
        if not Config.ENABLE_JIRA_INTEGRATION:
            return ""

        if not all([Config.JIRA_SERVER_URL, Config.JIRA_USER_EMAIL, Config.JIRA_API_TOKEN]):
            return (
                "## Jira Integration\n\n"
                "_Jira integration is enabled but JIRA_SERVER_URL, JIRA_USER_EMAIL, "
                "or JIRA_API_TOKEN is not configured._"
            )

        # Find highest-risk fix from FixerAgent output
        fixer_out: dict[str, Any] = state.tool_outputs.get("fixer", {})
        fixes: list[dict[str, Any]] = fixer_out.get("fixes", [])
        if not fixes:
            return (
                "## Jira Integration\n\n"
                "_No fixes were generated — no Jira ticket created._"
            )

        # Pick the fix with the highest dynamic_risk_score (already sorted Critical-first)
        top_fix = max(fixes, key=lambda f: float(f.get("dynamic_risk_score", 0.0)))

        cve_id = top_fix.get("cve_id", "N/A")
        risk_score = float(top_fix.get("dynamic_risk_score", 0.0))
        service = top_fix.get("service", "")
        target = top_fix.get("ip", state.target)

        # Choose the primary remediation code based on REMEDIATION_FORMAT
        if Config.REMEDIATION_FORMAT == "ansible":
            code = top_fix.get("ansible_task", top_fix.get("bash_snippet", ""))
            fmt = "ansible"
        else:
            code = top_fix.get("bash_snippet", top_fix.get("ansible_task", ""))
            fmt = "bash"

        # Build a human-readable description from CVE records embedded in the fix
        description = (
            f"{top_fix.get('title', 'Security finding')}. "
            f"Severity: {top_fix.get('severity', 'Unknown')}. "
            f"Port: {top_fix.get('port', 'N/A')}. "
            f"Notes: {top_fix.get('notes', '')}"
        )

        try:
            from integrations.jira_client import JiraEnterpriseClient
            client = JiraEnterpriseClient(
                server_url=Config.JIRA_SERVER_URL,
                user_email=Config.JIRA_USER_EMAIL,
                api_token=Config.JIRA_API_TOKEN,
                project_key=Config.JIRA_PROJECT_KEY,
            )
            ticket_url = client.create_remediation_ticket(
                cve_id=cve_id,
                risk_score=risk_score,
                description=description,
                remediation_code=code,
                fmt=fmt,
                target=target,
                service=service,
            )
            return (
                "## Jira Integration\n\n"
                f"A remediation ticket was automatically created for the highest-risk "
                f"finding (`{cve_id}`, score {risk_score}):\n\n"
                f"**Ticket:** [{ticket_url}]({ticket_url})\n\n"
                f"*Project: `{Config.JIRA_PROJECT_KEY}` | "
                f"Format: `{fmt}` | "
                f"Service: {service or 'N/A'}*"
            )
        except Exception as exc:  # noqa: BLE001
            return (
                "## Jira Integration\n\n"
                f"_Ticket creation failed: {exc}_\n\n"
                "Check `JIRA_SERVER_URL`, `JIRA_USER_EMAIL`, and `JIRA_API_TOKEN` in `.env`."
            )

    # =========================================================================
    # Utilities
    # =========================================================================

    @staticmethod
    def _fmt(obj: Any) -> str:
        """Serialise *obj* to indented JSON string for LLM prompt injection."""
        return json.dumps(obj, indent=2)
