"""
agents/report_agent.py
Report generation agent: consolidates all pipeline findings into a
structured Markdown penetration-testing report.

Design principle:
  - Structured sections (tables, finding blocks) are built directly
    from RTAIState data in Python — no LLM hallucination risk.
  - Narrative sections (Executive Summary, Recommendations, Conclusion)
    are generated by the LLM, given the structured data as context.
  - The two halves are stitched together and written to disk.
"""
from __future__ import annotations

import re
from datetime import datetime, timezone
from typing import Any

from langchain_core.messages import HumanMessage, SystemMessage

from agents.base_agent import BaseAgent
from core.config import Config
from core.state import RTAIState


# Risk ordering used to sort findings tables
_RISK_ORDER = {"critical": 0, "high": 1, "medium": 2, "low": 3, "n/a": 4}


class ReportAgent(BaseAgent):
    role = "Penetration Test Report Writer"
    goal = (
        "Produce a clear, professional penetration-testing report that an "
        "executive can skim and a technical engineer can act on."
    )

    def run(self, state: RTAIState) -> dict[str, Any]:
        # ── Structured sections (Python-built, deterministic) ──────────────
        recon_section        = self._build_recon_section(state)
        osint_section        = self._build_osint_section(state)
        exploit_section      = self._build_exploit_section(state)
        remediation_section  = self._build_remediation_section(state)

        # ── Narrative sections (LLM-generated) ────────────────────────────
        narrative = self._generate_narrative(state, osint_section, exploit_section,
                                             remediation_section)

        # ── Assemble full report ───────────────────────────────────────────
        date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        report_md = "\n\n".join([
            self._header(state, date_str),
            narrative["executive_summary"],
            self._scope_section(state, date_str),
            recon_section,
            osint_section,
            exploit_section,
            remediation_section,
            narrative["conclusion"],
        ])

        # ── Persist to disk ────────────────────────────────────────────────
        safe_name = re.sub(r"[^\w\-]", "_", state.engagement_name or "engagement")
        report_path = Config.REPORT_DIR / f"{safe_name}_{date_str}_report.md"
        report_path.write_text(report_md, encoding="utf-8")

        return {
            "report": report_md,
            "current_step": "report_complete",
            "finished": True,
        }

    # =========================================================================
    # Structured section builders
    # =========================================================================

    def _header(self, state: RTAIState, date_str: str) -> str:
        return (
            f"# Penetration Test Report\n\n"
            f"| Field | Value |\n"
            f"|---|---|\n"
            f"| **Engagement** | {state.engagement_name or 'N/A'} |\n"
            f"| **Target** | `{state.target}` |\n"
            f"| **Date** | {date_str} |\n"
            f"| **Classification** | CONFIDENTIAL |\n"
        )

    def _scope_section(self, state: RTAIState, date_str: str) -> str:
        return (
            "## Scope & Methodology\n\n"
            f"- **Target scope:** `{state.target}`\n"
            f"- **Assessment date:** {date_str}\n"
            "- **Methodology:** Automated pipeline — Reconnaissance (Nmap) → "
            "OSINT intelligence gathering (Tavily) → Exploitation analysis → "
            "Remediation planning → Report\n"
            "- **Tools:** python-nmap, Tavily Search API, OpenAI LLM\n"
        )

    def _build_recon_section(self, state: RTAIState) -> str:
        recon = next((f for f in state.findings if f.get("phase") == "recon"), None)
        if not recon:
            return "## Reconnaissance\n\n_No recon data available._"

        nmap_data = recon.get("nmap_raw", {})
        hosts = nmap_data.get("hosts", [])

        lines = ["## Reconnaissance\n"]
        if not hosts:
            lines.append("_No live hosts discovered._")
            return "\n".join(lines)

        for host in hosts:
            hostname = host.get("hostname") or host.get("host", "")
            lines.append(f"### Host: `{host.get('host')}` ({hostname})\n")
            lines.append(f"**State:** {host.get('state', 'unknown')}\n")

            # OS guesses
            os_matches = host.get("os_matches", [])
            if os_matches:
                lines.append("**OS Detection:**")
                for os in os_matches:
                    lines.append(f"- {os.get('name')} (accuracy: {os.get('accuracy')}%)")
                lines.append("")

            # Ports table
            ports = host.get("ports", [])
            if ports:
                lines.append("| Port | Protocol | Service | Product | Version |")
                lines.append("|---|---|---|---|---|")
                for p in ports:
                    lines.append(
                        f"| {p.get('port')} | {p.get('protocol')} | "
                        f"{p.get('service', '')} | {p.get('product', '')} | "
                        f"{p.get('version', '')} |"
                    )
                lines.append("")

        # LLM recon analysis
        llm_analysis = recon.get("llm_analysis", "")
        if llm_analysis:
            lines.append("### Recon Analysis\n")
            lines.append(llm_analysis)

        return "\n".join(lines)

    def _build_osint_section(self, state: RTAIState) -> str:
        osint = next((f for f in state.findings if f.get("phase") == "osint"), None)
        if not osint:
            return "## OSINT Intelligence\n\n_No OSINT data available._"

        lines = ["## OSINT Intelligence\n"]

        services = osint.get("services_researched", [])
        if services:
            lines.append(f"**Services researched:** {', '.join(f'`{s}`' for s in services)}\n")

        # Top 3 risks table (structured data from OsintAgent)
        top_3 = osint.get("top_3_risks", [])
        if top_3:
            lines.append("### Top 3 High-Risk Findings\n")
            lines.append("| Rank | Service | Type | Identifier | CVSS | Description | Source |")
            lines.append("|---|---|---|---|---|---|---|")
            for r in sorted(top_3, key=lambda x: x.get("rank", 99)):
                src = r.get("source_url", "N/A")
                src_cell = f"[link]({src})" if src.startswith("http") else src
                lines.append(
                    f"| {r.get('rank')} | {r.get('service')} | {r.get('type')} | "
                    f"`{r.get('identifier')}` | {r.get('cvss')} | "
                    f"{r.get('description')} | {src_cell} |"
                )
            lines.append("")

        # Analyst synthesis
        synthesis = osint.get("llm_synthesis", "")
        if synthesis:
            lines.append("### OSINT Analyst Summary\n")
            lines.append(synthesis)

        return "\n".join(lines)

    def _build_exploit_section(self, state: RTAIState) -> str:
        exploit = next(
            (f for f in state.findings if f.get("phase") == "exploit_analysis"), None
        )
        if not exploit:
            return "## Exploitation Analysis\n\n_No exploitation analysis available._"

        lines = [
            "## Exploitation Analysis\n",
            exploit.get("attack_vectors", "_No attack vectors recorded._"),
        ]
        return "\n".join(lines)

    def _build_remediation_section(self, state: RTAIState) -> str:
        remediation_finding = next(
            (f for f in state.findings if f.get("phase") == "remediation"), None
        )
        if not remediation_finding:
            return "## Remediation Plan\n\n_No remediation data available._"

        remediations: list[dict[str, Any]] = remediation_finding.get("remediations", [])
        if not remediations:
            return "## Remediation Plan\n\n_No attack vectors required remediation._"

        lines = ["## Remediation Plan\n"]

        # Summary table — one row per finding, sorted Critical-first
        lines.append("| # | Title | Risk | Service | CVE |")
        lines.append("|---|---|---|---|---|")
        for r in remediations:
            lines.append(
                f"| {r.get('id')} | {r.get('title')} | **{r.get('risk_level')}** | "
                f"{r.get('service')} | `{r.get('cve')}` |"
            )
        lines.append("")

        # Detailed subsection per remediation
        for r in remediations:
            lines.append(f"### {r.get('id')}. {r.get('title')}\n")
            lines.append(f"**Risk:** {r.get('risk_level')} &nbsp;|&nbsp; "
                         f"**Service:** {r.get('service')} &nbsp;|&nbsp; "
                         f"**CVE:** `{r.get('cve')}`\n")

            steps = r.get("steps", [])
            if steps:
                lines.append("**Steps:**")
                for i, step in enumerate(steps, 1):
                    lines.append(f"{i}. {step}")
                lines.append("")

            snippet = r.get("code_snippet")
            if snippet:
                lines.append("**Commands / Config:**")
                lines.append("```bash")
                lines.append(snippet)
                lines.append("```\n")

            verification = r.get("verification")
            if verification and verification != "N/A":
                lines.append(f"**Verification:** `{verification}`\n")

        return "\n".join(lines)

    # =========================================================================
    # LLM narrative generator
    # =========================================================================

    def _generate_narrative(
        self,
        state: RTAIState,
        osint_section: str,
        exploit_section: str,
        remediation_section: str,
    ) -> dict[str, str]:
        """
        Ask the LLM to write two narrative sections.
        Returns a dict with keys: executive_summary, conclusion.
        (Recommendations are now covered by the structured Remediation Plan section.)
        """
        import json as _json
        osint_finding   = next((f for f in state.findings if f.get("phase") == "osint"), {})
        exploit_finding = next(
            (f for f in state.findings if f.get("phase") == "exploit_analysis"), {}
        )
        remediation_finding = next(
            (f for f in state.findings if f.get("phase") == "remediation"), {}
        )

        top_3_risks    = osint_finding.get("top_3_risks", [])
        attack_vectors = exploit_finding.get("attack_vectors", "None")
        remediations   = remediation_finding.get("remediations", [])

        messages = [
            SystemMessage(content=self._system_prompt()),
            HumanMessage(
                content=(
                    f"Engagement: {state.engagement_name}\n"
                    f"Target: {state.target}\n\n"
                    f"Top 3 OSINT risks:\n{self._fmt(top_3_risks)}\n\n"
                    f"Attack vectors:\n{attack_vectors}\n\n"
                    f"Remediation plan summary ({len(remediations)} items):\n"
                    f"{self._fmt([{'id': r.get('id'), 'title': r.get('title'), 'risk_level': r.get('risk_level')} for r in remediations])}\n\n"
                    "Write two sections of a penetration-testing report.\n"
                    "Return ONLY valid JSON (no markdown fences) in this shape:\n"
                    "{\n"
                    '  "executive_summary": "## Executive Summary\\n\\n<content>",\n'
                    '  "conclusion": "## Conclusion\\n\\n<content>"\n'
                    "}\n\n"
                    "Guidelines:\n"
                    "- Executive Summary: 3-5 sentences for a non-technical audience; "
                    "  state the overall risk posture, number of critical/high findings, "
                    "  and that a full remediation plan is included.\n"
                    "- Conclusion: 2-3 sentences wrapping up the engagement and encouraging "
                    "  re-testing after remediations are applied.\n"
                )
            ),
        ]
        response = self.llm.invoke(messages)

        try:
            parsed = _json.loads(response.content)
            return {
                "executive_summary": parsed.get("executive_summary",
                                                "## Executive Summary\n\n_Not generated._"),
                "conclusion":        parsed.get("conclusion",
                                                "## Conclusion\n\n_Engagement complete._"),
            }
        except (_json.JSONDecodeError, KeyError):
            return {
                "executive_summary": f"## Executive Summary\n\n{response.content}",
                "conclusion":        "## Conclusion\n\n_Engagement complete._",
            }

    # =========================================================================
    # Utilities
    # =========================================================================

    @staticmethod
    def _fmt(obj: Any) -> str:
        import json
        return json.dumps(obj, indent=2)
